
tablas={'double_deep_crossbars' : 'VIGA TIPO CAJA DE DOBLE PROFUNDIDAD DE 2.5',
'double_deep_floors' : 'SUELOS DE DOBLE PROFUNDIDAD',
'double_deep_floor_reinforcements' : 'REFUERZOS PARA EL SUELO DE DOBLE PROFUNDIDAD',
'double_deep_heavy_load_frames' : 'BASTIDORES DE CARGA PESADA DE DOBLE PROFUNDIDAD',
'double_deep_joist_box25s' : 'VIGA TIPO CAJA DE DOBLE PROFUNDIDAD DE 2.5',
'double_deep_joist_box25_caliber14s' : 'VIGA TIPO CAJA DE DOBLE PROFUNDIDAD DE 2.5 CALIBRE 14',
'double_deep_joist_box2s' : 'VIGA TIPO CAJA DE DOBLE PROFUNDIDAD DE 2',
'double_deep_joist_box2_caliber14s' : 'VIGA TIPO CAJA DE DOBLE PROFUNDIDAD DE 2 CALIBRE 14',
'double_deep_joist_c2_s' : 'VIGA DE DOBLE PROFUNDIAD TIPO C2',
'double_deep_joist_chairs' : 'VIGA DE DOBLE PROFUNDIAD TIPO SILLA',
'double_deep_joist_l25_caliber14s' : 'VIGA TIPO L DE DOBLE PROFUNDIDAD DE 2.5 CALIBRE 14',
'double_deep_joist_l25_s' : 'VIGA TIPO L DE DOBLE PROFUNDIDAD DE 2.5 ',
'double_deep_joist_l2_caliber14s' : 'VIGA TIPO L DE DOBLE PROFUNDIDAD DE 2 CALIBRE 14',
'double_deep_joist_l2_s' : 'VIGA TIPO L DE DOBLE PROFUNDIDAD DE 2 ',
'double_deep_joist_lrs' : 'VIGA DE DOBLE PROFUNDIAD TIPO LR',
'double_deep_joist_structurals' : 'VIGA DE DOBLE PROFUNDIAD TIPO ESTRUCTURAL',
'double_deep_miniature_frames' : 'MARCOS EN MINIATURA DE DOBLE PROFUNDIDAD',
'double_deep_spacers' : 'ESPACIADOR DE DOBLE PROFUNDIDAD',
'double_deep_structural_frames' : 'MARCOS ESTRUCTURALES DE DOBLE PROFUNDIDAD',
'freights' : 'FLETES',
'grills' : 'PARRILLA',
'installations' : 'INSTALACION',
'packagings' : 'FLETE',
'quot25_j_galvanized_panels' : 'PANELES GALVANIZADOS VIGA L DE 2.5 IN ',
'quot25_j_painted_panels' : 'PANELES PINTADOS VIGA L DE 2.5 IN',
'quot2_j_galvanized_panels' : 'PANELES GALVANIZADOS VIGA L DE 2.0 IN',
'quot2_j_painted_panels' : 'PANELES PINTADOS VIGA L DE 2.0 IN',
'quotation_administratives' : 'ADMINISTRATIVO',
'quotation_installs' : 'INSTALACION',
'quotation_protectors' : 'PROTECTORES',
'quotation_specials' : 'ESPECIAL',
'quotation_travel_assignments' : 'VIATICOS ',
'quotation_uninstalls' : 'DESINTALACION',
'quot_chair_j_galvanized_panels' : 'PANELES GALVANIZADOS SILLA',
'quot_chair_j_painted_panels' : 'PANELES PINTADOS  SILLA',
'selective_crossbars' : 'CROSSBAR',
'selective_floors' : 'PISO',
'selective_floor_reinforcements' : 'PISO REFORZADO',
'selective_heavy_load_frames' : 'MARCO',
'selective_joist_box25s' : 'TIPO CAJA DE 2.5 CALIBRES: 10, 12 y 16',
'selective_joist_box25_caliber14s' : 'TIPO CAJA DE 2.5 CALIBRE: 14',
'selective_joist_box2s' : 'TIPO CAJA DE 2.0 CALIBRES: 10, 12 y 16',
'selective_joist_box2_caliber14s' : 'TIPO CAJA DE 2.0 CALIBRE: 14',
'selective_joist_c2_s' : 'TIPO C2',
'selective_joist_chairs' : 'TIPO SILLA',
'selective_joist_l25_caliber14s' : 'TIPO L 2.5 CALIBRE 14',
'selective_joist_l25_s' : 'TIPO L 2.5 CALIBRES: 10, 12 y 16 ',
'selective_joist_l2_caliber14s' : 'TIPO L 2.0 CALIBRE 14',
'selective_joist_l2_s' : 'TIPO L 2.0 CALIBRES: 10, 12 y 16',
'selective_joist_lrs' : 'TIPO LR',
'selective_joist_structurals' : 'TIPO ESTRUCTURAL',
'selective_miniature_frames' : 'MARCOS EN MINIATURA',
'selective_spacers' : 'DISTANCIADORES',
'selective_structural_frames' : 'MARCOS ESTRUCTURALES',
'uninstalls' : 'DESINSTALACION',
'wood' : 'MADERAS',}